angular/material.angular.io

- src/index.html
R: @tinayuangao 
I've already configured analytics to ignore `localhost` and `material2-docs-dev`
> chore: add google analytics tag

- src/app/pages/homepage/homepage.html
- src/app/pages/homepage/homepage.ts
From pr #9 
R: @mmalerba @jelbourn
> feat(homepage): Use static content in homepage

- src/app/app-module.ts
- src/app/pages/component-category-list/component-category-list.ts
- src/app/pages/component-sidenav/component-sidenav.ts
- src/app/pages/guide-list/guide-list.html
- src/app/pages/guide-list/guide-list.scss
- src/app/pages/guide-list/guide-list.ts
- src/app/pages/guide-list/index.ts
- src/app/pages/guide-viewer/guide-viewer.html
- src/app/pages/guide-viewer/guide-viewer.ts
- src/app/pages/guide-viewer/index.ts
- src/app/routes.ts
- src/app/shared/doc-viewer/doc-viewer.ts
- src/app/shared/guide-items/guide-items.spec.ts
- src/app/shared/guide-items/guide-items.ts
- src/app/shared/navbar/navbar.html
- src/app/shared/shared-module.ts
> Add a guide list and a guide viewer to show guides

- src/_app-theme.scss
- src/app/material-docs-app.html
- src/app/material-docs-app.scss
- src/app/material-docs-app.ts
- src/app/pages/component-category-list/_component-category-list-theme.scss
- src/app/pages/component-category-list/component-category-list.html
- src/app/pages/component-category-list/component-category-list.scss
- src/app/pages/component-category-list/component-category-list.ts
- src/app/pages/component-list/_component-list-theme.scss
- src/app/pages/component-list/component-list.html
- src/app/pages/component-list/component-list.scss
- src/app/pages/component-sidenav/component-sidenav.html
- src/app/pages/component-sidenav/component-sidenav.scss
> category list styles

- src/_app-theme.scss
- src/index.html
* Fixes the app background being cut off below the fold.
* Removes the "Loading..." sign while loading.
> fix: app background cut off

- firebase.json
- src/app/examples/example-module.ts
- src/app/examples/snack-bar-component/snack-bar-component-example-snack.css
- src/app/examples/snack-bar-component/snack-bar-component-example-snack.html
- src/app/examples/snack-bar-component/snack-bar-component-example.html
- src/app/examples/snack-bar-component/snack-bar-component-example.ts
- src/app/examples/snack-bar-overview/snack-bar-overview-example.ts
* Only open on button click
* Always add a duration they they _eventually_ go away
> Fix snackbar example auto-opening and never closing

- .firebaserc
- README.md
- package.json
It is assumed that the deployer has access to both instances (dev and prod)
> Publish scripts

- src/app/examples/progress-bar-configurable/progress-bar-configurable-example.html
- src/app/examples/progress-spinner-configurable/progress-spinner-configurable-example.html
fixes https://github.com/angular/material2/issues/2756
> fix(spinner): fixed binding the the radio buttons model

- src/app/pages/component-viewer/_component-viewer-theme.scss
- src/styles/_typography-theme.scss
fixes https://github.com/angular/material2/issues/2689
> fix(readability): changed text opacity from .54 to .87 according the spec

- src/app/examples/example-module.ts
Fix plunker example for snack-bar-component 
R: @jelbourn
> Add additional files to snack bar component example

- src/app/pages/homepage/homepage.html
It's been bugging me for a while now, thought I'd just get it over with.
> Add OCD dot to first promo description

- src/assets/img/homepage/material_splash.svg
This returns the homepage splash SVG to its original look.
> fix(homepage): fix splash svg on homepage

- tools/fetch-assets.sh
* Adds the `--depth` option when cloning the assets for the docs.
R: @jelbourn
> build: faster fetch script for assets

- src/app/pages/homepage/homepage.html
This image shows the problem: https://i.stack.imgur.com/UZtTT.png
> fix: Homepage last svg image scale for small devices

- src/index.html
* Includes the `Roboto` font from Google Fonts. Previously only `Roboto Mono` was included.
* Includes the Web animations polyfill in order for the component animations to work on all browsers.
> fix: include proper font and web animations polyfill

- src/styles/_markdown-theme.scss
- src/styles/_markdown.scss
Polishes the inline code example styles by adding ascent colors and padding.
**light**
**dark**
> chore(style): added polish to code snippet examples

- src/app/shared/footer/footer.html
https://wwww.angular.io -> https://angular.io
> fix(footer): extra w in www.angular.io

- src/app/pages/component-category-list/component-category-list.spec.ts
- src/app/pages/component-category-list/component-category-list.ts
- src/app/pages/guide-list/guide-list.ts
- src/app/pages/guide-viewer/guide-viewer.ts
- src/app/pages/homepage/homepage.ts
- src/app/pages/page-title/page-title.spec.ts
- src/app/pages/page-title/page-title.ts
Addresses #189 by setting page titles by enhancing the ComponentPageTitle service.
> feat(docs): add page titles to doc pages #189

- angular-cli.json
- ngsw-manifest.json
- package.json
- src/assets/img/favicons/manifest.json
Adds Service Workers for PWA #175 
Will address app-shell rendering in separate PR for #169
> feat(PWA): add service worker #175

- src/app/pages/component-sidenav/component-sidenav.ts
> fix: sidenav autohiding

- src/highlightjs/material-dark.css
- src/highlightjs/material-light.css
- src/index.html
- src/styles/_general.scss
Updates the color theme to: https://developers.google.com/web/fundamentals/architecture/app-shell
> chore(styles): update styles to match google theme

- angular-cli.json
Removes Service Workers per #304
> chore(sw): remove sw for time being

- src/app/shared/guide-items/guide-items.ts
> Add elevation guide to guide-items

- src/app/app-module.ts
TODO: Remove usage of deprecated HttpModule
> add http client module for table http example

- ngsw-manifest.json
- src/index.html
Fixes not all of the required Roboto font weights being included on the docs site.
> fix: missing roboto font weights

- LICENSE
- src/app/shared/footer/footer.html
- src/app/shared/stackblitz/stackblitz-writer.spec.ts
- src/app/shared/stackblitz/stackblitz-writer.ts
> chore: bump year

- README.md
It has been removed. See here for discussion + alternatives: https://github.com/angular/angular-cli/issues/4659
> Removed github pages ng command

- src/styles/_api-theme.scss
Removes accent on method header name for visibility. Addresses #398
> fix: update title background #398

- src/assets/stackblitz/styles.css
**Before** 
**After**
**Example Viewer**
> style: match stackblitz and example viewer padding

- src/app/shared/guide-items/guide-items.ts
> docs: add schematics link

- karma.conf.js
Followup to https://github.com/angular/material.angular.io/pull/431
> fix: fix 'reporters' key name in karma.conf

- src/assets/stackblitz/main.ts
Fixes https://github.com/angular/material2/issues/11147
> chore: add MatBadgeModule to stackblitz main.ts file.

- firebase.json
Sets browser cache for these assets to expire after one week
> Add cache expiration header for js, html, and css

- src/styles/_markdown.scss
Fixes overflow on devices
Addresses https://github.com/angular/material2/issues/11693
> fix: overflow on devices

- package-lock.json
- package.json
Fixes a warning when running the `lint` script.
> chore: fix lint warning

- src/app/shared/documentation-items/documentation-items.ts
* Adds the ripples to the documentation items
> feat: add ripples to documentation items

- src/app/shared/documentation-items/documentation-items.ts
Reverts angular/material.angular.io#489
> Revert "feat: add ripples to documentation items"

- src/app/shared/example-viewer/_example-viewer-theme.scss
Fixes the code sample tabs always showing a horizontal scrollbar for Windows users.
> fix: horizontal scrollbar always visible on Windows in code samples

- scripts/ci/build-and-test.sh
> build: fix CI tests after change to postinstall script

- src/assets/stackblitz/material-module.ts
fixes Virtual Scroll Stackblitz examples
Fixes #546
> fix(scrolling): add ScrollingModule

- README.md
- add more links to deployments
- add guidance on where to open issues
- add links to where source content comes from
- fix instructions for running locally
- add some troubleshooting notes
Fixes #498
> docs(readme): update contributing instructions

- src/main.ts
its already loaded in index.html from the Google CDN
> fix(main): don't load hammerjs twice

- LICENSE
- src/app/shared/footer/footer.html
- src/app/shared/stackblitz/stackblitz-writer.spec.ts
- src/app/shared/stackblitz/stackblitz-writer.ts
> Update year to 2019

- src/app/pages/component-sidenav/component-sidenav.spec.ts
> test: component sidenav spec incorrectly creates MediaQueryList object

- src/app/pages/component-list/component-list.html
> build: fix object might be undefined error in template

- .github/ISSUE_TEMPLATE/docs-infra.md
> chore: add issue template

- src/app/pages/component-sidenav/component-sidenav.scss
Please check that your PR fulfills the following requirements:
Content on mobile devices overflows on certain pages in CDK.
Issue Number: 
#550 
Content does not overflow anymore.
Before
After
> fix(docs): correct overflow cdk pages

- src/app/pages/component-sidenav/component-sidenav.scss
Cherry pick a couple CSS fixes from `master`.
> fix(component-sidenav): apply CSS fixes from master to 8.x

- src/app/pages/component-sidenav/component-sidenav.scss
Fixes issue introduced in #651
> fix api docs content from displaying after the left nav

- src/app/pages/component-category-list/component-category-list.html
needed with the router's `relativeLinkResolution: 'corrected'`
Fixes #661
> fix(category-list): bad routerLink path with relativeLinkResolution

- src/app/shared/stack-blitz/stack-blitz-button.html
> fix(stack-blitz-button): use open_in_new icon

- src/styles/_api-theme.scss
- src/styles/_api.scss
- src/styles/_tables.scss
Adds styles needed for https://github.com/angular/components/pull/17813.
> Add styles for async methods marker

- src/app/pages/guide-viewer/guide-viewer.ts
> fix(guide): add ReactiveFormsModule to GuideViewerModule

- package.json
- src/app/pages/component-sidenav/component-sidenav.ts
- src/app/pages/component-viewer/component-viewer.spec.ts
- src/app/shared/example-viewer/example-viewer.html
- src/app/shared/example-viewer/example-viewer.spec.ts
- src/app/shared/example-viewer/example-viewer.ts
- src/app/shared/stack-blitz/stack-blitz-writer.spec.ts
- src/app/shared/stack-blitz/stack-blitz-writer.ts
- yarn.lock
* Blocked on angular/components#18547
> build: lazily load examples in docs site

- src/app/shared/documentation-items/documentation-items.ts
re: https://github.com/angular/components/pull/18456
> add table-reorderable example

- package.json
- yarn.lock
> chore(ci): workaround ngcc crash due to running out of memory

- src/app/material-docs-app.html
- src/app/material-docs-app.scss
- src/app/material-docs-app.ts
- src/app/pages/component-category-list/component-category-list.html
- src/app/pages/component-category-list/component-category-list.ts
- src/app/pages/component-page-header/component-page-header.html
- src/app/pages/component-sidenav/component-sidenav.html
- src/app/pages/component-sidenav/component-sidenav.ts
- src/app/pages/component-viewer/component-api.html
- src/app/pages/component-viewer/component-examples.html
- src/app/pages/component-viewer/component-overview.html
- src/app/pages/component-viewer/component-viewer.html
- src/app/pages/component-viewer/component-viewer.ts
- src/app/pages/guide-list/guide-list.html
- src/app/pages/guide-list/guide-list.ts
- src/app/pages/guide-viewer/guide-viewer.html
- src/app/pages/guide-viewer/guide-viewer.ts
- src/app/pages/homepage/homepage.html
- src/app/pages/homepage/homepage.ts
- src/app/shared/navbar/navbar.html
- src/app/shared/navbar/navbar.scss
- src/app/shared/navbar/navbar.ts
- src/app/shared/navigation-focus/navigation-focus.ts
A soft nav should auto focus on the content and a hard nav should have the next focus element as skip link.
A hard nav is a full page load (e.g. when coming to the app from another site), a soft nav is a route change within the app. These terms are further explained in https://dzone.com/articles/quick-primer-to-single-page-application-spa-and-tr
> add skip navigation link

- src/app/shared/documentation-items/documentation-items.ts
Reflect change in https://github.com/angular/components/pull/19142
> rename example to reflect change in @angular/components-example

- src/app/shared/documentation-items/documentation-items.ts
Exposes the docs for all of the testing modules that we have available.
> fix: expose component testing modules

- scenes/src/app/scene-viewer/scene-viewer.ts
fixing lint error from previous PR
> change from using host property to using @HostBinding

- scenes/src/app/app.module.ts
- scenes/src/app/scene-overlay-container.ts
- scenes/src/app/scene-viewer/scene-viewer.html
custom overlay container to make sure overlay components also get filtered for scene screenshots
> custom overlay container

- scenes/src/app/app-routing.module.ts
- scenes/src/app/scenes/table/table-scene.html
- scenes/src/app/scenes/table/table-scene.scss
- scenes/src/app/scenes/table/table-scene.ts
> add table scene

- scenes/src/app/app-routing.module.ts
- scenes/src/app/scenes/tabs/tabs-scene.html
- scenes/src/app/scenes/tabs/tabs-scene.scss
- scenes/src/app/scenes/tabs/tabs-scene.ts
> tabs scene

- scenes/src/app/app-routing.module.ts
- scenes/src/app/scenes/sort/sort-scene.html
- scenes/src/app/scenes/sort/sort-scene.scss
- scenes/src/app/scenes/sort/sort-scene.ts
> sort scene

- README.md
- use shorter command for updating content and examples
- minor grammar improvements
> docs(readme): add v9 and v10 links

- src/app/pages/guide-list/_guide-list-theme.scss
- src/app/pages/guide-list/guide-list.html
- src/app/pages/guide-list/guide-list.scss
- src/app/pages/guide-list/guide-list.ts
demo: https://material2-docs-dev.web.app/guides
> reformat guides page using cards

- src/app/pages/component-sidenav/component-sidenav.scss
Fixes https://github.com/angular/components/issues/20313
> fix: router outlet should not allow overflow

- src/app/shared/example-viewer/example-viewer.html
- src/app/shared/stack-blitz/stack-blitz-button.ts
- src/app/shared/stack-blitz/stack-blitz-writer.spec.ts
- src/app/shared/stack-blitz/stack-blitz-writer.ts
- src/assets/stack-blitz-tests/.editorconfig
- src/assets/stack-blitz-tests/.gitignore
- src/assets/stack-blitz-tests/angular.json
- src/assets/stack-blitz-tests/browserslist
- src/assets/stack-blitz-tests/package.json
- src/assets/stack-blitz-tests/src/app/material-module.ts
- src/assets/stack-blitz-tests/src/index.html
- src/assets/stack-blitz-tests/src/main.ts
- src/assets/stack-blitz-tests/src/polyfills.ts
- src/assets/stack-blitz-tests/src/styles.scss
- src/assets/stack-blitz-tests/src/test.ts
- src/assets/stack-blitz-tests/src/test/jasmine-setup.ts
- src/assets/stack-blitz-tests/tsconfig.app.json
- src/assets/stack-blitz-tests/tsconfig.json
- src/assets/stack-blitz-tests/tsconfig.spec.json
- src/assets/stack-blitz-tests/tslint.json
demo with button harness example: https://material2-docs-dev.web.app/components/button/examples
> feat(stackblitz): add new stackblitz template to run harness test examples

- src/styles/_markdown-theme.scss
* Fixes https://github.com/angular/components/issues/20426
> fix(button): fix color of mat-button links

- src/index.html
Updates to the newer version of the Google Fonts snippet.
Related to https://github.com/angular/components/pull/21479.
> fix: use new Google Fonts snippet

- package.json
- src/assets/stack-blitz-tests/package.json
- src/assets/stack-blitz/package.json
- tools/npm/check-npm.js
- yarn.lock
- same script as in the angular/components repo
- update `@types/node` in StackBlitz
> build: give a warning when trying to npm install

- src/assets/versions.json
This PR fixes version list issue in v9
#962
> update versions.json for v9.material.angular.io

- src/assets/versions.json
This PR fixes version list issue in v8
#962
> update versions.json for v8.material.angular.io

- package.json
- yarn.lock
Relates to https://github.com/angular/components/pull/22608. Relates to https://github.com/angular/components/issues/22409.
> build: update MDC to match the version required by v11.2.2+

- src/app/pages/component-sidenav/component-sidenav.scss
Fixes a bug in sidenav where user has to scroll to bottom of the page to reach bottom of navigation
Fixes #857
> fix(sidenav): unable to scroll sidenav as expected

- src/app/shared/documentation-items/documentation-items.ts
Exposes the docs for `cdk/coercion` and `cdk/collections`.
Fixes https://github.com/angular/components/issues/19530.
Fixes https://github.com/angular/components/issues/18818.
**Note:** I'll submit a PR on the main repo add some examples to the coercion overview so it isn't so bare.
> feat: expose coercion and collections docs

- src/app/shared/theme-picker/theme-picker.ts
Fix unselected theme picker when localStorage is empty.
Fixes #204
> fix(material/theme): unselected theme picker

- src/app/shared/footer/footer.scss
Fixes Angular Material footer logo for IE11
Fixes #1027
> fix: angular material footer logo

- scenes/src/test.ts
- src/test.ts
Opts the docs site into the new test module teardown behavior.
> build: enable unit test teardown

- src/index.html
Remove duplicated meta tag for `theme-color` at line 48 and keep the tag at line 14
> fix: remove duplicated meta tag

- src/app/app-module.ts
- src/app/pages/homepage/homepage.scss
- src/app/pages/homepage/homepage.ts
- src/app/shared/carousel/carousel.scss
- src/app/shared/carousel/carousel.ts
- src/app/shared/table-of-contents/_table-of-contents-theme.scss
- src/app/shared/version-picker/version-picker.html
Makes it so that we disable all animations if the user prefers reduced motion.
> feat: add support for reduced motion

- .circleci/config.yml
> build: fix circleci rebase to work with other branches than `master`

- src/app/pages/component-sidenav/component-sidenav.ts
We accidentally had a deep import which was breaking the dev app deployment.
> fix: wrong import path

- package.json
- tools/audit-docs.js
- yarn.lock
We were behind on the versions of MDC which may be causing the deployment to fail.
> build: update version of MDC

- src/app/shared/documentation-items/documentation-items.ts
Preview: https://material2-docs-dev.web.app/cdk/listbox/overview
CARETAKER NOTE: merge this PR when releasing 14.2.0
> docs: Add cdk/listbox docs

- package.json
- yarn.lock
Updates the version of the docs content to include the fixes from https://github.com/angular/components/pull/25795.
> build: update docs content

- tools/audit-docs.js
With the recent Bazel refactorings, an URL to the audit script is no longer accepted. This is necesary though as we leverage that script for monitoring the docs site.
> build: allow for endpoint to be specified when auditing docs

- bazel-bin
- bazel-material.angular.io
- bazel-testlogs
> build: delete danging bazel symlinks

- src/assets/stack-blitz/src/material.module.ts
Fixes angular/components#26305
> fix material.module by adding CdkListboxModule

- .circleci/config.yml
Update to the latest RBE setup after key rotation.
> build: update to latest remote build execution setup

- angular.json
- firebase.json
> Remove quotes around `data:` in CSP

- src/app/shared/guide-items/guide-items.ts
Merge only once https://github.com/angular/components/pull/29054 is merged in
> feat: Add separate guide for M2 specific theming

- src/app/shared/version-picker/version-picker.ts
> feat: add ability to keep pathname and hash on version change

- src/app/shared/example-viewer/example-viewer.html
> Fix code viewer title and buttons disappearing

- src/app/pages/component-sidenav/component-sidenav.html
- src/app/pages/component-sidenav/component-sidenav.ts
- src/app/pages/component-viewer/component-viewer.ts
Some optional queries were incorrectly marked as required which was throwing runtime errors.
> fix: errors when reading optional queries

- src/app/pages/component-sidenav/component-sidenav.spec.ts
- src/app/pages/component-sidenav/component-sidenav.ts
Fixes a lint issue and a type error.
> build: fix CI failures

- package.json
- src/app/pages/component-viewer/component-viewer.ts
- src/app/shared/stack-blitz/stack-blitz-writer.ts
- yarn.lock
Updates to rxjs 7 to fix the deployment and keep us up to date.
> fix: update to rxjs 7

- src/app/shared/navigation-focus/navigation-focus.spec.ts
Fixes a few tests that were failing after the standalone switch.
> fix: failing test
