angular/material.angular.io

.travis.yml
scripts/browserstack/block-tunnel.sh
scripts/browserstack/start-tunnel.sh

* When the tunnel didn't start properly after 2 minutes, the `block` script still waits 2 minutes until the timeout ends  (sum: 2 minutes unnecessary)
**Note**: This is the feedback from @jelbourn  and @hansl on `material2`

chore(ci): stop waiting for tunnel when tunnen couldn't start

---

src/_app-theme.scss
src/app/pages/component-viewer/_component-viewer-sidenav-theme.scss
src/app/pages/component-viewer/_component-viewer-theme.scss
src/app/pages/component-viewer/component-viewer-sidenav.scss
src/app/pages/component-viewer/component-viewer.html
src/app/pages/component-viewer/component-viewer.scss
src/app/pages/component-viewer/component-viewer.ts
src/main.scss

@jelbourn (cc/ @naomiblack, @amitafr ) 
Ok, sidenav styles are ready for review.

Sidenav styles

---

src/app/examples/example-data.ts
src/app/examples/example-module.ts

Add additional `-dialog.html` to plunker for dialog examples

---

src/app/examples/example-data.ts
tools/plunker-example.sh

Change the example path.
R: @jelbourn

Add a script to copy example files to assets folder.

---

src/assets/plunker/index.html

* Removes the component bundle from the Plunker since it's unused.
* Adds `Arial` as a fallback font (as stated in material.google.com)
R: @jelbourn

fix: remove unnecessary components bundle

---

src/_app-theme.scss
src/app/shared/footer/_footer-theme.scss
src/app/shared/footer/footer.html
src/app/shared/footer/footer.scss

Added Angular logo and link to angular.io in footer to match microsite templates

add logo and link to angular in footer

---

src/app/pages/component-sidenav/component-sidenav.scss

This is a simple one-liner that removes the `md-sidenav-content` from the flow of `md-sidenav-layout` so that layout does not derive its scroll height from the content. 
On Safari with this fix, the `md-sidenav-content` matches its bounding box client rect height and scroll height to the layout which now is correctly flex'ed to the rest of the page's height. 
Closes #71

fix(scrolling): enable scrolling on safari

---

protractor.conf.js
src/assets/documents/guides/getting-started.html
src/assets/documents/guides/theming.html
src/assets/plunker/index.html
src/polyfills.ts

style(branding): branding consistency fixup

---

src/app/examples/progress-bar-configurable/progress-bar-configurable-example.html
src/assets/examples/progress-bar-configurable-example-html.html
src/assets/plunker/examples/progress-bar-configurable/progress-bar-configurable-example.html

* Fixes the progress-bar configurable example, where the `color` binding is set through an attribute instead of an Angular input binding.
References https://github.com/angular/material2/issues/2813
R: @kara

docs: fix progress-bar-configurable example

---

src/app/pages/component-category-list/component-category-list.scss

The component group card for "Buttons, Indicators & Icons" has a wrapped title which causes the card to be larger than the others. Reduced font-size to normalize each card's title to just a one-liner

fix: normalize card height

---

src/app/examples/list-sections/list-sections-example.css
src/app/examples/list-sections/list-sections-example.html
src/app/examples/list-sections/list-sections-example.ts

Fixes a typo where the icon was tagged with `md-list-avatar` instead of `md-list-icon` (already fixed in main repo).  Also changes the color of the list icon color to have better contrast for the example.

docs(list): fix list icon tag and styling

---

src/app/pages/component-viewer/component-viewer.scss

The tab styles for the docs page use a direct chain from a custom class to avoid styling tabs found in examples.

fix(styling): example tabs should not be styled

---

src/app/pages/homepage/homepage.html
src/app/shared/navbar/navbar.html
src/main.scss

Removes styling from button examples

style(button): explicitly style docs buttons

---

src/_app-theme.scss
src/app/pages/guide-list/_guide-list-theme.scss
src/app/pages/guide-list/guide-list.html
src/app/pages/guide-list/guide-list.scss

Adds on top of #80, but I remove the `<table>` since it's not quite right to use that inside of a list. 
I also changed the `h1` style to be regular text.

Use md-nav-list for guide list

---

LICENSE
karma.conf.js
package.json
src/app/shared/footer/footer.html
src/app/shared/plunker/plunker-writer.spec.ts
src/app/shared/plunker/plunker-writer.ts

* Updates all Angular dependencies to the latest RC.
* Fixes any errors/warnings caused by the upgrade.
* Fixes error when running the unit tests.
* Bumps the year in the license.
**Note:** This depends on a release of Material that includes https://github.com/angular/material2/pull/3608. I've made an assumption that it'll be `beta.3`.

feat: angular 4 compatibility

---

tools/fetch-assets-local.sh

Adds a script for building and fetching material assets locally. Addresses #172

chore(build): add script for fetching assets locally #172

---

tools/fetch-assets-local.sh

Updates the fetch-local script to always build the material docs and examples on every run.

chore(scripts): update fetch-local to always build #173

---

src/app/shared/plunker/plunker-button.ts

* Fixes that the Plunker form does not contain the source-files from the associated example.
Fixes https://github.com/angular/material2/issues/5245

fix: plunkers not including source files

---

package.json
tools/fetch-assets-local.sh

* Currently the `fetch-assets-local` script tries to copy every `.html` file to the `src/assets` folder.
This includes multiple `README.html` files. Bash at this point complains that there are multiple files with the same name are copied to the same destination.
* Also ensures that the CWD of the fetch script is always the root of the project.

build: fix fetch assets local script

---

src/app/shared/theme-picker/theme-storage/theme-storage.ts

Prevents the site from crashing on browsers that don't allow access to localStorage (e.g. IE11 or iOS Safari in private mode).

fix: site crashing on browsers with limited localStorage access

---

angular-cli.json
src/assets/custom-themes/pink-bluegrey.scss
src/assets/custom-themes/purple-green.scss
src/highlightjs/material-dark.css
src/highlightjs/material-light.css

Update highlightjs to use material style syntax for light and dark themes.
**light**
**dark**

chore(styles): apply material light / dark styles to highlightjs

---

src/app/pages/component-viewer/component-viewer.html
src/app/pages/component-viewer/component-viewer.scss
src/app/pages/guide-viewer/guide-viewer.html
src/app/pages/guide-viewer/guide-viewer.scss
src/styles/_constants.scss

Fixes https://github.com/angular/material.angular.io/issues/197
Also applies to same concept to the guide viewer

style(viewers): set max width and center content

---

src/app/pages/component-viewer/component-viewer.ts
src/app/routes.ts

It closes the issue [#5229](https://github.com/angular/material2/issues/5229) from Material2 repo.

fix(routes): fix error on invalid urls

---

src/app/pages/component-list/component-list.ts
src/app/pages/guide-viewer/guide-viewer.ts
src/app/routes.ts

Related to #191.
Actually it throws the following error:
> Cannot read property 'document' of undefined
... when navigate to url like: https://material.angular.io/guide/anything
This PR fixes this.
@jelbourn

fix: error on invalid routes

---

src/app/pages/component-viewer/_component-viewer-theme.scss
src/app/pages/component-viewer/component-viewer.scss
src/app/shared/example-viewer/_example-viewer-theme.scss
src/app/shared/example-viewer/example-viewer.scss

Fixes a bug where if you open the [cdk guide source viewer](https://material.angular.io/guide/cdk-table) without previously loading a component, there is no padding.

fix(source-viewer): Move docs-example-source styles to the appropriate component

---

src/app/shared/doc-viewer/doc-viewer.ts

-This fixes an issue where, on slow connections, requests would unnecessarily stack up if the user navigates components & tabs faster than requests can complete

fix(doc-viewer): cancel previous pending requests when changing url

---

src/app/app-module.ts
src/app/material-docs-app.ts
src/app/pages/homepage/homepage.html

- Navbar shadow wasn't being shown at [`/categories/forms`](https://material.angular.io/categories/forms) due to only checking for `/components` in the start of the url
- Check only one navigation event (end) and `urlAfterRedirects` when setting shadow/scoll-position (prevents bug where going to [`/componentsfoo`](https://material.angular.io/componentsfoo) results in improper shadow)
- Fix bug where GET STARTED links break after a redirect to the homepage
The last one is weird. If you go to [`/foo`](https://material.angular.io/foo) and are redirected back to the homepage, the GET STARTED url is serialized improperly. It looks like some issue with `ApplyRedirects#apply` and I'm pretty sure is a bug in core. The fix is to use an absolute path.

fix(navbar): shadow and routing

---

src/app/pages/component-category-list/component-category-list.html
src/app/pages/component-category-list/component-category-list.scss

This matches the category list behavior to the component list. Before, it was not possible to navigate the list by focusing a card and pressing <kbd>enter</kbd>

fix(categories): make list items anchors like component list items

---

src/app/shared/table-of-contents/table-of-contents.ts

Fix: Table of contents show the word "link" on IE and Edge

---

src/styles/_markdown.scss

Small styling addition for lists to keep them the same as paragraphs (`font-size` and `line-height`). 
This fixes #254.

docs(style): apply list styling

---

src/app/pages/component-sidenav/component-sidenav.scss

Addresses #247 where scrolling doesn't work on safari.

bug(docs): fix scroll broken on safari #247

---

src/app/shared/documentation-items/documentation-items.ts

This updates the example in the documentation to the new overview example.
https://github.com/angular/material2/pull/5666/

docs(demos): updates dialog example to overivew

---

src/app/shared/plunker/plunker-writer.ts

For https://github.com/angular/material2/issues/6952

fix: Add thumbup-icon to assets when loading icon-svg-example plunkr.

---

src/app/shared/copier/copier.service.ts
src/app/shared/doc-viewer/doc-viewer-module.ts
src/app/shared/doc-viewer/doc-viewer.spec.ts
src/app/shared/doc-viewer/doc-viewer.ts
src/app/shared/example-viewer/_example-viewer-theme.scss
src/app/shared/example-viewer/example-viewer.html
src/app/shared/example-viewer/example-viewer.scss
src/app/shared/example-viewer/example-viewer.spec.ts
src/app/shared/example-viewer/example-viewer.ts

- This basically copies the feature from core/aio 
- I made the button hide/show on hover since it was distracting while switching between tabs
Fixes https://github.com/angular/material.angular.io/issues/221

feat(example-viewer): add copy text button

---

src/app/material-docs-app.html
src/app/material-docs-app.scss
src/app/material-docs-app.ts
src/app/pages/component-viewer/component-overview.scss
src/app/pages/component-viewer/component-viewer.scss
src/app/pages/component-viewer/component-viewer.ts
src/app/pages/guide-viewer/guide-viewer.scss
src/app/pages/homepage/homepage.scss
src/app/shared/navbar/_navbar-theme.scss
src/app/shared/navbar/navbar.html
src/app/shared/navbar/navbar.scss
src/app/shared/navbar/navbar.spec.ts
src/app/shared/navbar/navbar.ts
src/styles/_api-theme.scss
src/styles/_constants.scss
src/styles/_general.scss
src/styles/_markdown.scss
src/styles/_tables.scss

- Make navbar "sticky" on all pages
- Show table of contents (non-sticky) at the top of pages on mobile
- Shrink landing page spacing on mobile to increase density
- Move navbar to a two row version on mobile
- Use md-icon for angular and github icons in navbar
- Enforce word breaks for p tags in docs, preventing x axis overflows
- Decrease height of Guides subheader to match other pages
- Shrink docs-api table spacing on mobile to increase density

fix: Make site more mobile friendly

---

src/app/pages/component-page-header/component-page-header.scss
src/app/pages/guide-viewer/guide-viewer.scss

* Fixes bug where guides were no longer centered on wide viewports
* Fixes https://github.com/angular/material.angular.io/issues/269
cc @jelbourn

fix: center guide viewer and remove outline from focused header

---

src/app/pages/component-viewer/component-api.scss
src/app/pages/component-viewer/component-viewer.ts

This PR adds the better spacing to the API docs.
Relies on: https://github.com/angular/material2/pull/7457

Fixes API Docs Formatting

---

package-lock.json
src/app/app-module.ts
src/app/pages/component-category-list/component-category-list.html
src/app/pages/component-category-list/component-category-list.spec.ts
src/app/pages/component-category-list/component-category-list.ts
src/app/pages/component-list/component-list.html
src/app/pages/component-list/component-list.spec.ts
src/app/pages/component-list/component-list.ts
src/app/pages/component-sidenav/component-sidenav-can-load-guard.ts
src/app/pages/component-sidenav/component-sidenav.html
src/app/pages/component-sidenav/component-sidenav.spec.ts
src/app/pages/component-sidenav/component-sidenav.ts
src/app/pages/component-viewer/component-viewer.html
src/app/pages/component-viewer/component-viewer.ts
src/app/routes.ts
src/app/shared/documentation-items/documentation-items.spec.ts
src/app/shared/documentation-items/documentation-items.ts
src/app/shared/navbar/navbar.html
src/app/shared/navbar/navbar.ts

feat: Prepare for adding CDK docs

---

src/app/pages/component-viewer/component-overview.scss
src/app/pages/component-viewer/component-viewer.scss
src/app/shared/example-viewer/_example-viewer-theme.scss
src/styles/_general.scss

Fixes https://github.com/angular/material.angular.io/issues/236

fix(example-viewer): don't wrap code samples

---

src/assets/plunker/systemjs.config.js

* Adds missing CDK package mappings to the Plunker SystemJS configuration.
**Note**: Those are not really used right now. We don't have examples for most of the CDK stuff yet, but it's still good to keep it in sync with the Plunker template config.

chore(plunkers): include missing cdk mappings

---

package.json
src/app/pages/component-sidenav/_component-sidenav-theme.scss
src/app/pages/component-sidenav/component-nav.html
src/app/pages/component-sidenav/component-sidenav.html
src/app/pages/component-sidenav/component-sidenav.scss
src/app/pages/component-sidenav/component-sidenav.ts
src/app/pages/component-viewer/component-viewer.scss
src/app/shared/table-of-contents/_table-of-contents-theme.scss
src/app/shared/table-of-contents/table-of-contents.scss
src/index.html

feat(nav): new sidenav

---

src/app/pages/guide-list/guide-list.scss

- This allows the nav-list to reach full width of container on small screen
- In wide screens, this increases the margin to better match other constants in the app
cc @jelbourn

style(guide-list): remove margin on small screens

---

src/app/pages/component-viewer/component-api.html
src/app/pages/component-viewer/component-overview.html
src/app/pages/component-viewer/component-viewer.spec.ts
src/app/pages/component-viewer/component-viewer.ts
src/app/shared/documentation-items/documentation-items.spec.ts
src/app/shared/documentation-items/documentation-items.ts
src/app/shared/table-of-contents/table-of-contents.ts

Goes along with https://github.com/angular/material2/pull/7675.
I've done some ugly things here- any suggestions on cleaning it up without hard-coding a bunch of repetitive stuff?
I'm also doing something weird with the router because I don't know the real way.

Disambiguate between material and cdk docs

---

src/app/pages/component-viewer/component-viewer.scss
src/app/pages/guide-viewer/guide-viewer.scss
src/app/shared/doc-viewer/header-link.ts
src/app/shared/table-of-contents/table-of-contents.scss

The TOC component shouldn't need to know that it's sticky or what it's width should be.
This also removes a class from header-link that was being used in two different contexts.
cc @jelbourn

refactor(toc): move layout styles out of component and into parents

---

src/app/shared/doc-viewer/doc-viewer.ts

By default fragment links are referring to the root page and the actual hash won't matter anymore. This can be fixed in a similar way to the `header-link` directive by updating the anchor URLs to include the current base URL.
Since those are normal links and aren't `header-links`, the `header-link` directive is not an option. A directive that updates the links accordingly would be perfect, but there is no way to interpolate directives on those HTML templates dynamically.
Having a component that creates/wraps the anchor elements is wrong and adds more pain than it helps. The links should can be just updated using simple DOM manipulation.
Fixes https://github.com/angular/material2/issues/8503

fix: create proper fragment urls

---

src/app/pages/component-category-list/component-category-list.ts
src/app/pages/component-sidenav/component-sidenav.ts

Hey, I am new to OSS and this would be my first contribution. Please review the PR.

Page title is not correctly updated (#296)

---

src/app/shared/doc-viewer/doc-viewer.ts

External links with a hash are incorrectly updated, because they are considered as hash links that are referring to a local anchor on the current page (fragment links).
Fixes https://github.com/angular/material2/issues/8994

fix: external links with hash are updated incorrectly

---

src/app/shared/stackblitz/stackblitz-writer.ts
src/assets/stackblitz/main.ts

This PR fixes dialogs throwing errors when opened in stackblitz.
References:
- https://github.com/angular/material.angular.io/pull/228
- https://github.com/angular/material2/issues/8750

fix(stackblitz): fix dialogs not working #5899 #228 #8750

---

tools/fetch-assets.sh

* Updates the fetch assets to work on initial postinstall.
* Refactors the fetch assets script to be more clean and aligned with the material2/ scripts.
Related to https://github.com/angular/material2/pull/9100

build: fix fetch assets script

---

src/assets/stackblitz/main.ts

Current example is broken since it requires the new Http module.
Fixes #339

fix(table): http example needs httpclientmodule

---

src/app/routes.ts
src/app/shared/guide-items/guide-items.ts

* The cdk-table guide became the overview document for the cdk table component. Therefore it's no longer a guide.

chore: update guides to no longer include cdk-table

---

src/assets/stackblitz/main.ts

* Adds the `MatDividerModule` to the StackBlitz template files
Fixes https://github.com/angular/material2/issues/9618

chore: add divider module to stackblitz

---

src/app/pages/component-viewer/component-api.scss
src/styles/_api.scss

* Adds a dotted underline to the `Deprecated` markers. Those can be hovered to see more information about the deprecation / deletion.
* Fixes that the deprecation markers are too big and are not looking good in the API table
* Adds a line through property names that are also deprecated. This makes it clear that this API is deprecated and also looks pretty good.
References https://github.com/angular/material2/pull/9648

better styling for deprecated api items

---

src/app/shared/stackblitz/stackblitz-writer.ts

fixes angular/material2#9805
- also upgrades angular to 5.1.1

fix(stackblitz): update angular dependencies for stackblitz to latest

---

src/app/shared/stackblitz/stackblitz-writer.ts

This PR starts the stackblitz demo on the index file. Addresses #373

feat(stackblitz): start sb on index #373

---

src/app/app-module.ts
src/app/material-docs-app.ts
src/app/shared/ga/ga.ts
src/environments/environment.prod.ts
src/environments/environment.ts
src/index.html

Fixes https://github.com/angular/material2/issues/10022

chore: send analytics data on all navigation ends

---

src/app/shared/stackblitz/stackblitz-writer.ts

This PR fixes the SVG demo not getting the correct path. There is still an issue with the SVG not being resolved though. Reached out to Eric regarding.
See: https://stackblitz.com/edit/angular-niug11?file=app/icon-svg-example.ts

fix(stackblitz): fix svg path getting extra /app

---

package.json
src/app/shared/footer/footer.ts
src/app/shared/navbar/navbar.html
src/app/shared/navbar/navbar.ts
src/app/shared/stackblitz/stackblitz-writer.ts
src/app/shared/version-picker/index.ts
src/app/shared/version-picker/version-picker.html
src/app/shared/version-picker/version-picker.ts
src/app/shared/version/version.ts
tools/deploy.sh

- add version picker (using menu)
- make stackblitz use the same version as the doc site
Demo: https://material2-docs-dev.firebaseapp.com/

feat: add version and version picker

---

src/app/pages/component-viewer/component-viewer.ts

fix #327,
In the component-viewer, use id and section to check the navigation, but when the id and section is not matched, it always navigated to the Component page, so here is the issue: when navigating between Component page and CDK page, when the id is existed and not matched with section, always navigate to the Component page.
@jelbourn @mmalerba hope you can help me review, thanks

fix(component-viewer): can't navigate to CDK after visiting component

---

src/app/shared/documentation-items/documentation-items.ts
src/assets/stackblitz/main.ts

Adds the bottom sheet examples to the navigation and includes the bottom sheet module.
Related Material PR: https://github.com/angular/material2/pull/9809

chore: add bottom sheet examples

---

src/app/shared/documentation-items/documentation-items.ts

Includes all of the available menu examples under the menu "Examples" tab.

fix: include all menu examples under examples tab

---

src/app/shared/documentation-items/documentation-items.ts

Fixes one of the menu examples not rendering due to a typo.

fix: menu icons example not rendering

---

src/app/pages/component-sidenav/component-sidenav.scss

Fixes the body container collapsing on IE, causing the footer to show up right under the navigation.
For reference:

fix: footer not sticking to bottom of the page on IE

---

src/app/shared/documentation-items/documentation-items.ts

Fixes not all available autocomplete examples being listed under the "Examples" tab.

chore: show all autocomplete examples in examples tab

---

tools/deploy.sh
tools/fetch-assets.sh

* Currently the `fetch-assets` script always fetches the data from the `master` branch. This is problematic because if we release a new patch release, we will incorrectly have the docs content for the upcoming major version. Adds the possibility to fetch the docs-content from a given branch (e.g. `6.4.x`)
* Adds a small note to the `deploy` script that makes the publisher aware of the docs-content, which should be kept updated.
This is related to https://github.com/angular/material2/pull/12690#event-1790790389

build: ensure docs-content is up-to-date before deploy

---

src/app/shared/documentation-items/documentation-items.ts

Not sure whether coercion is something we want to show though. Also the `coerceArray` description feels a bit unclear to me.

docs: show text-field, coercion and platform in CDK docs

---

src/app/pages/component-category-list/component-category-list.html
src/app/pages/component-category-list/component-category-list.scss
src/app/pages/component-category-list/component-category-list.ts
src/app/pages/component-list/_component-list-theme.scss
src/app/pages/component-list/component-list.html
src/app/pages/component-list/component-list.scss
src/app/shared/documentation-items/documentation-items.ts
src/app/shared/navbar/navbar.html

This PR adds short (max. two-line) summaries to all list cards across the documentation to provide more context to the user before they navigate to the documentation. A short paragraph is also added at the top of the two category list pages ("Components"/"CDK") to provide some context to those.
Currently I feel like there is not enough information on the documentation list pages to A) explain where you are and B) hint at where you want to go. This means that users could be sent a link like https://material.angular.io/cdk/categories and have the following questions:
- What is the CDK? What does it stand for? Why would I use it instead of "normal" Angular Material?
- What is in the "Components" menu item and how is that different from the "Components" button in the toolbar?
Alternatively, …

feat: add summaries to all menu items and category pages

---

src/app/shared/documentation-items/documentation-items.ts

Exposes all of the available chips examples under the "Examples" tab.

chore: expose all chips examples under examples tab

---

src/app/shared/documentation-items/documentation-items.ts

* Adds the ripples to the documentation items 
(Ripple examples depend on: https://github.com/angular/material2/commit/d7967765c2509160a260e741a1696c35df3bc35a)
---
**CARETAKER NOTE**: Merge **only** before a new **minor** version is being published (e.g. `6.5.0`).
cc. @mmalerba

feat: add ripples to documentation items

---

src/app/pages/component-viewer/component-api.html
src/app/pages/component-viewer/component-examples.html
src/app/pages/component-viewer/component-overview.html
src/app/pages/component-viewer/component-viewer.ts
src/app/pages/guide-viewer/guide-viewer.html
src/app/shared/doc-viewer/doc-viewer.ts
src/app/shared/doc-viewer/header-link.ts
src/app/shared/navigation-focus/navigation-focus.ts

* Currently if someone visits a link that contains a fragment that refers to an anchor element, the element won't be scrolled into view properly. This is because the `focusOnNavigation` calls `focus()` after the scroll into view. This causes the focused element to be visible in view.
* Removes an unnecessary workaround for fixing fragment URLs.
Fixes #396

fix: anchor links not scrolling into view

---

src/app/shared/documentation-items/documentation-items.ts

* Corrects the capitalization for the "Drag and Drop" menu item.
* Enables some examples that were waiting for the 6.3.0 release.

chore: capitalization on nav item and enable commented out examples

---

src/app/shared/version-picker/version-picker.html
src/app/shared/version-picker/version-picker.ts

A simple, but important change -
Added an arrow dropdown icon to the version picker. In my opinion, it is need immediately obvious that you can change versions. (I wasted a lot of time looking for the A5 website the other day). It doesn't really look interactive, it looks like it's just telling me the most recent version. 
A dropdown icon will make it more apparent that you can switch between A5 and A6 documentation.

Added dropdown icon to version picker

---

src/app/material-docs-app.ts

We intentionally reset the scroll position on navigation if the component view changed (e.g. if you switch from components/button to components/slider). Unfortunately this outdated check causes the CDK ToC to not work. This has been like that for V6 as well.
In order to make the ToC work for the CDK, we need to make sure that we don't reset the scroll position if someone navigates within a CDK doc entry.

fix: table of contents not working within cdk

---

package-lock.json
src/app/shared/theme-picker/theme-picker.html
src/app/shared/theme-picker/theme-picker.spec.ts
src/app/shared/theme-picker/theme-picker.ts
src/app/shared/theme-picker/theme-storage/theme-storage.spec.ts
src/app/shared/theme-picker/theme-storage/theme-storage.ts

* Reworks the theming setup to store only the current theme's name, rather than the entire object in `localStorage`. This is more robust for the cases where we want to change the theme object's interface.
* Adds the ability to link people to the docs site with a particular theme (e.g. https://material.angular.io?theme=purple-green). This allows us to preview the theme. For example we can use it for https://github.com/angular/material2/issues/13708 to show people what the theme would look like when they're prompted in a schematic.

feat: add the ability to link to the site with a particular theme

---

src/app/shared/documentation-items/documentation-items.ts

* Fixes that the sticky table examples does not load (see: angular/material2#13872)
* Adds the new cdk platform overview example to the `Examples` section as well.
Closes angular/material2#13872.

fix: sticky table example not loading

---

src/app/shared/stackblitz/stackblitz-writer.ts

Closes angular/material2#13975

chore: update StackBlitz examples to use Angular v7

---

src/app/shared/example-viewer/example-viewer.spec.ts

Our test data is overwritten by `Object.assign` because the `example-module` now always has `additionalFiles` set to an empty array.

build: fix unit test after example-module refactor

---

src/app/shared/doc-viewer/doc-viewer.spec.ts
src/app/shared/doc-viewer/doc-viewer.ts

Fixes https://github.com/angular/material2/issues/13875

fix: correct links in doc-viewer markdown files to have the proper base value

---

src/app/shared/documentation-items/documentation-items.ts

Includes the appearance example in the list of examples for the form field.
Relates to https://github.com/angular/material2/issues/14400.

chore: include form field appearance example

---

src/assets/stackblitz/material-module.ts

There are some examples that depend on the `A11yModule` and they break if they're forked into a Stackblitz, because we don't import the `A11yModule` directly anywhere.
Fixes https://github.com/angular/material2/issues/14761

fix: missing import for a11y module

---

src/app/shared/documentation-items/documentation-items.ts

Exposes all of the available stepper examples under the "Examples" tab.

chore: expose more stepper examples

---

src/assets/stackblitz/material-module.ts

There are some examples that depend on the `PortalModule` and they break
if they're forked into a Stackblitz, because we don't import the `PortalModule`
directly anywhere.
Fixes https://github.com/angular/material2/issues/15175

fix: missing import for `PortalModule`

---

src/app/pages/component-sidenav/component-sidenav.ts
src/app/pages/component-viewer/component-viewer.ts

This is the result of the static-query ng-update schematic. Mostly ran it for testing, but should be good to keep if we update the app to V8-beta.

chore: run explicit static-query timing migration

---

src/app/shared/footer/footer.html
src/app/shared/footer/footer.scss

Links to the full license from the footer, similar to angular.io. Note that it links to the repo since we don't have a dedicated license page.
Fixes https://github.com/angular/components/issues/16039.

chore: link to full license from footer

---

src/assets/stackblitz/index.html
src/index.html

Along the same lines as https://github.com/angular/components/pull/16093. Sets the `display` parameter when loading fonts for better control over how they're loaded.

chore: set display when loading fonts

---

src/assets/stackblitz/main.ts
src/assets/stackblitz/material-module.ts

Removes the imports from `@angular/material` since they end up breaking some of the examples once they're forked to Stackblitz.

fix: remove imports from top-level package

---

src/assets/img/favicons/manifest.json

fixes #599
The paths are broken and the escapes "\" are unnecessary. Also, there is no longer `density` member in the spec. It was removed a few years ago.

fix(manifest.json): use rel paths, remove density

---

README.md
package.json
yarn.lock

- npm -> yarn
- more updates from Angular Material -> Angular Components
- add details on material2-docs-content repo
- correct development setup steps
- update to latest material2-docs-content
- postinstall task uses build-themes task
Fixes #578. Closes #583.

docs(readme): update and corrections

---

src/app/pages/component-list/component-list.ts
src/app/pages/component-sidenav/component-sidenav.ts
src/app/pages/component-viewer/component-viewer.spec.ts
src/app/pages/component-viewer/component-viewer.ts
src/app/pages/guide-viewer/guide-viewer.html
src/app/pages/guide-viewer/guide-viewer.spec.ts
src/app/pages/guide-viewer/guide-viewer.ts
src/app/shared/copier/copier.service.ts
src/app/shared/doc-viewer/doc-viewer.spec.ts
src/app/shared/doc-viewer/doc-viewer.ts
src/app/shared/documentation-items/documentation-items.ts
src/app/shared/example-viewer/example-viewer.spec.ts
src/app/shared/guide-items/guide-items.ts
src/app/shared/stackblitz/stackblitz-writer.spec.ts
src/app/shared/svg-viewer/svg-viewer.ts
src/app/shared/table-of-contents/table-of-contents.spec.ts
src/app/shared/table-of-contents/table-of-contents.ts
src/app/shared/theme-picker/theme-picker.ts
src/tsconfig.json

align with the examples and the new CLI settings by enabling
- `noImplicitAny`
- `noImplicitReturns`
- `noImplicitThis`
- `noFallthroughCasesInSwitch`
- `strictNullChecks`
Relates to https://github.com/angular/angular-cli/pull/14905

refactor: enable stricter TypeScript compiler flags

---

src/assets/custom-themes/pink-bluegrey.scss

fix(a11y): improve contrast of accent in pink-bluegrey theme

---

src/app/pages/component-sidenav/_component-sidenav-theme.scss
src/app/pages/guide-list/_guide-list-theme.scss
src/app/shared/table-of-contents/_table-of-contents-theme.scss
src/highlightjs/material-dark.scss
src/highlightjs/material-light.scss
src/styles/_api-theme.scss
src/styles/_markdown-theme.scss

All contrast ratios are now above `4.5`.
Fixes #398. Reverts #399.
I also ran into https://github.com/angular/components/issues/17152, but that example needs to be fixed in the Components repo.

fix(a11y): various issues with contrast ratios

---

tsconfig.app.json

Please check that your PR fulfills the following requirements:
Ivy isn't enabled for `8.x`.
Issue Number: N/A
Ivy is enabled for `8.x`.
Current material.angular.io
zipped production bundle - 853 KB
unzipped bundle resources - 4.3 MB
With Ivy enabled
zipped production bundle - 645 KB ✅
unzipped bundle resources - 2.4 MB ✅
Made possible by getting https://github.com/angular/components/pull/17282 and https://github.com/angular/components/pull/17228 merged back to `8.2.3`.

build: enable Ivy for 8.x

---

src/app/pages/component-sidenav/component-sidenav.scss

Please check that your PR fulfills the following requirements:
`box-sizing` is declared twice.
Issue Number: 
Not applicable.
Removed one instance.
I saw this mistake while fixing #550

refactor: remove duplicate css declaration

---

angular.json
src/_app-theme.scss
src/styles.scss

- pull palette and theme definitions into `_app-theme.scss`
- rename `main.scss` to `styles.scss` to align with CLI
- disable commonChunk generation in CLI
- changes reduce production app size by 9 KB

refactor: styles refactoring. disable commonChunk

---

src/app/pages/component-sidenav/component-sidenav.scss

(cherry picked from commit bb92e3632627daca7e126e2853cac0dfbb9ad3f7)

8.x: fix api docs content from displaying after the left nav

---

src/app/pages/component-sidenav/component-sidenav.scss
src/app/pages/component-viewer/component-api.html
src/app/pages/component-viewer/component-examples.html
src/app/pages/component-viewer/component-overview.html
src/app/pages/component-viewer/component-viewer.ts
src/app/pages/guide-viewer/guide-viewer.html
src/app/shared/doc-viewer/doc-viewer.ts
src/app/shared/documentation-items/documentation-items.ts
src/app/shared/table-of-contents/table-of-contents.html
src/app/shared/table-of-contents/table-of-contents.scss
src/app/shared/table-of-contents/table-of-contents.spec.ts
src/app/shared/table-of-contents/table-of-contents.ts

Allows the API tab to include additional documentation files to be added to the page, making sure the table of contents also updates with them.
Primary objective is to allow the testing harness API docs to be appended to the component API page, e.g. button harness APIs will show up after the button APIs

add option for additional api docs for testing harnesses

---

src/app/pages/component-category-list/component-category-list.html
src/app/shared/stack-blitz/stack-blitz-button.html

fix(category-list): bad routerLink path with relativeLinkResolution (#663)
needed with the router's `relativeLinkResolution: 'corrected'`
Fixes #661
fix(stack-blitz-button): use open_in_new icon (#667)
Fixes #662

fix: apply updates from master to 8.x branch

---

src/app/shared/documentation-items/documentation-items.ts

Requires https://github.com/angular/components/pull/17779

Rename `Testing > Testing` to `Testing > Component Harnesses`

---

src/app/material-docs-app.ts
src/app/pages/component-viewer/component-viewer.ts
src/app/shared/table-of-contents/table-of-contents.ts
src/app/shared/theme-picker/theme-picker.ts
tsconfig.json

- enable Ivy's strict Template Type Checking
- fix related build errors
- complete `this._destroyed` in `ngOnDestroy()`
- exclude `dist/` from linting
`strictPropertyInitialization` is a bit more problematic, so it will be handled in a separate PR.

build: enable strictTemplates, strictBindCallApply, and strictFunctionTypes

---

src/app/app-module.ts
src/app/pages/component-category-list/component-category-list.ts
src/app/pages/component-list/component-list.ts
src/app/pages/component-page-header/component-page-header.ts
src/app/pages/component-sidenav/component-sidenav-can-load-guard.ts
src/app/pages/component-sidenav/component-sidenav.ts
src/app/pages/component-viewer/component-viewer.ts
src/app/pages/guide-list/guide-list.ts
src/app/pages/guide-viewer/guide-viewer.ts
src/app/pages/homepage/homepage.ts
src/app/pages/page-title/page-title.ts
src/app/routes.ts
src/app/shared/doc-viewer/doc-viewer-module.ts
src/app/shared/ga/ga.ts
src/app/shared/navbar/navbar.ts

This PR implements the first round of lazy loading for the site. In general, the only significant impact is on the bundle size reduction for the home page and the guide list. 
The guides themselves should also see a significant reduction in bundle size, but they depend upon the `DocViewer` which depends on the `ExampleViewer` which pulls in the full `@angular/components-examples` along with every Angular Material and CDK component.
This is the first step towards solving #176, which calls out the concerns with `ExampleViewer`. `ExampleViewer` isn't tied to a route, so we can't lazy load it the normal way.
Most Guide's only need the `DocViewer`, but the following 3 guides do actually require the `ExampleViewer`:
- Creating a custom form field control
- Using elevation helpers
- Creating a …

Lazy load documentation modules

---

src/assets/stack-blitz/src/main.ts

Can be tested via https://angularmaterial.dev/components/datepicker/examples
Relates to https://github.com/angular/components/issues/14792 and https://github.com/angular/components/pull/18252.
This should go into `master` ASAP for the v9 final release.

fix(stack-blitz): default to form-field fill appearance

---

src/app/pages/component-viewer/component-api.html
src/app/pages/component-viewer/component-viewer.ts
src/app/shared/documentation-items/documentation-items.ts

The CDK test harness documentation API has `test-harnesses` as id. This
doesn't match any generated API document since the API doc for
`@angular/cdk/testing` is generated with the `cdk-testing` id.
We should add support for custom API doc ids that differ from the
actual doc entry id in order to fix this issue.
Fixes angular/components#18426

fix: cdk test harness API document not found

---

src/app/pages/component-viewer/component-api.html

Currently the docs look like this on pages with additional API docs (test harness docs)

fix: components with multiple API docs do not display correctly

---

.circleci/config.yml

We generate a lot of chunks with our build. To improve stability and to reduce the amount it takes to run, we use a higher resource class with better VM specs.

build: use better resource class for building in circleci

---

src/app/pages/component-viewer/component-overview.html
src/app/pages/component-viewer/component-viewer.ts
src/app/shared/documentation-items/documentation-items.ts
src/app/shared/stack-blitz/stack-blitz-button.ts
src/app/shared/stack-blitz/stack-blitz-writer.spec.ts
src/app/shared/stack-blitz/stack-blitz-writer.ts
yarn.lock

With https://github.com/angular/components/commit/ce22f1b3444ad006f00cb95f338e6f2e142d559b, we changed how the docs-content
is composed. Instead of always putting all files at the top-level
of the `docs-content/`, files are now nested based on their structure
in `angular/components` repository. This ensures that there no collisions
for such files, and that multiple files with same file can exist in the docs-content.
The docs app needs to be updated to account for these new paths.

refactor: account for collision avoidance changes to docs-content

---

src/app/pages/component-viewer/component-api.html
src/app/pages/component-viewer/component-viewer.ts
src/app/shared/table-of-contents/table-of-contents.ts

Link sections were inserted in the order Angular rendered them, which I guess is non-deterministic (now?). 
Fixes #731

fix: explicitly set an index for each API docs section

---

src/app/shared/example-viewer/example-viewer.spec.ts
src/app/shared/example-viewer/example-viewer.ts

The recent changes to account for the docs-content have been merged. Unfortunately though it seems like parts of the changes have been lost (for the highlighted example files) for whatever reason (maybe rebasing).
This follow-up PR adds the remaining parts needed to account for the docs-content restructure. It ensures that the highlighted example files can be loaded in the docs.

Follow up to example-viewer for collision docs-content change

---

src/app/shared/documentation-items/documentation-items.ts

The ripple overview does not load currently because it's a special
generated file that does not match an entry-point, and is nested
under `material/core/ripple`. This does not match other documentation
items for which we infer the overview path based on the doc item `id`.

fix: ripple overview not loading

---

src/styles/_markdown.scss

Prevent site header from headbutting text headers when navigating using fragment links.

Fragment link navigation padding

---

src/app/shared/stackblitz/stackblitz-writer.ts

fix(stack-blitz): v7 demos fail when trying to load v9 dependencies

---

src/app/material-docs-app.scss
src/app/material-docs-app.ts
src/app/pages/component-category-list/component-category-list.html
src/app/pages/component-list/component-list.html
src/app/pages/component-list/component-list.ts
src/app/pages/component-sidenav/component-sidenav.ts
src/app/pages/component-viewer/component-viewer.html
src/app/pages/guide-list/guide-list.html
src/app/pages/guide-viewer/guide-viewer.html
src/app/pages/homepage/homepage.html
src/app/shared/navbar/navbar.html
src/app/shared/navbar/navbar.ts
src/app/shared/navigation-focus/navigation-focus.service.ts
src/app/shared/navigation-focus/navigation-focus.spec.ts
src/app/shared/navigation-focus/navigation-focus.ts
src/app/shared/table-of-contents/table-of-contents.ts

Currently there are several places in the app try to track navigation events and properly redirect focus. The current approach is rather brittle, it would be better to coordinate it through a globally available service.
This service can manage:
- Allowing directives to request that the skip link jump to them
- Deciding which element will actually receive focus from the skip link
- Differentiating between hard and soft navigations

refactor: create a service to manage navigation & focus state in the docs app

---

src/assets/stack-blitz/src/styles.scss

I don't remember why this was deeppurple-amber, but I think the StackBlitz theme should be the same as the default site theme.

Change stackblitz theme to indigo-pink

---

src/app/shared/documentation-items/documentation-items.ts

slide toggle and tabs had incorrect prefix and were not loading examples

patch: fix incorrect prefix for loading examples

---

src/app/pages/component-viewer/component-examples.html
src/app/shared/doc-viewer/doc-viewer.spec.ts
src/app/shared/doc-viewer/doc-viewer.ts
src/app/shared/example-viewer/_example-viewer-theme.scss
src/app/shared/example-viewer/code-snippet.html
src/app/shared/example-viewer/code-snippet.ts
src/app/shared/example-viewer/example-viewer.html
src/app/shared/example-viewer/example-viewer.spec.ts
src/app/shared/example-viewer/example-viewer.ts

Extract fields from html generated from embedded example comments in md docs to generate compact view examples.
(extra: update button colours to be consistent)

enable compact view examples

---

src/app/pages/component-category-list/_component-category-list-theme.scss
src/app/pages/component-category-list/component-category-list.html
src/app/pages/component-category-list/component-category-list.scss
src/app/pages/component-sidenav/_component-sidenav-theme.scss
src/app/pages/component-sidenav/component-sidenav.ts
src/app/shared/documentation-items/documentation-items.ts

follow up of https://github.com/angular/material.angular.io/pull/760
- change color/hover of side nav
- hover effect on cards
- text wrap constraint on cards

follow-up improvements to components list page

---

src/app/shared/navbar/navbar.scss

skip link was off centered 
`left: 44%` looked fine on most laptop screens but won't be centered on bigger/smaller screens

center skip link

---

src/app/pages/guide-list/guide-list.html
src/app/pages/guide-list/guide-list.scss
src/app/pages/guide-list/guide-list.spec.ts

On the cdk and components pages the footer always displays below the bottom of the viewport whereas
on the guides page it displays in the middle of the page when viewed on larger devices. This fix
ensures that the guides page takes up 100% of the given viewport and the footer is displayed
outside the viewport matching the other pages.
----- 
example of current functionality

fix(guides): fix the positioning of the footer on the guides page

---

src/app/shared/guide-items/guide-items.ts

add overview for guides to display in the carousel on the home page
will also be useful when revamping the guides page

add overviews for guides

---

src/app/pages/component-category-list/_component-category-list-theme.scss

fix(component-category-list): links fail a11y contrast checks in dark mode

---

src/index.html
src/styles/_markdown-theme.scss

Code snippets on the doc site use Roboto Mono with `font-weight: 300` this caused it to be hard to read on Windows.
- add `font-weight: 400` for Roboto Mono
- change border around static snippets to visually separate them from surrounding text and to be consistent with live snippets
`font-weight: 400` without border change:
`font-weight: 400` with border change:
dark mode:

update code snippet view

---

src/app/shared/example-viewer/example-viewer.html
src/app/shared/example-viewer/example-viewer.ts

There were a couple of issues that were causing the "Copy to clipboard" button to copy the content of the first tab:
1. It was hardcoded to look at the first `snippet` component.
2. Even if we were using the `selectedTab` to get a reference to the open tab content, it wouldn't have worked because we kept setting the `selectedTab` based on the passed in `file`. These changes make it so the tab group propagates its selected index back to the `selectedTab`.
Fixes https://github.com/angular/components/issues/19867.

fix: copy to clipboard button always copying content of first tab

---

src/app/material-docs-app.scss

The home and guide pages are scrollable, but they felt janky because they didn't use the native accelerated scrolling.

fix: homepage not using native accelerated scrolling on touch devices

---

src/app/pages/homepage/homepage.scss

Current View:
After this change:
Modified to 250px:
Let me know which looks good
fixes #833

fix: home page in mobile view

---

src/app/pages/guide-viewer/guide-viewer.scss

While a guide is loading we show a loading message and the page compresses down which causes the footer to show up for a split second. These changes add a style that always pushes the footer off the viewport.
For reference:

fix: footer jumping up while guide is loading

---

src/assets/stack-blitz/src/app/material-module.ts

Add overlayModule import in material-module
Fixes https://github.com/angular/components/issues/19997

docs-bug(CDK:Overlay): Stackblitz example broken

---

package.json
src/app/shared/example-viewer/example-viewer.spec.ts
src/app/shared/example-viewer/example-viewer.ts
yarn.lock

We recently refactored how our docs-content example module is composed.
We did this because the docs app assumes path in the docs-content
package that are not necessarily always correct. i.e. breaking the chips
drag and drop example.
Additionally the docs-content example module is now more self-contained
so that assumptions about files inside of an example are not required
anymore. i.e. examples can now _not_ have CSS or HTML files. Previously
we always had to display an empty CSS/HTML file (which is confusing).
See: https://github.com/angular/components/pull/20003

refactor: prepare for docs-content changes in v10.1

---

src/app/pages/guide-viewer/guide-viewer.scss
yarn.lock

Fixes a regression caused by #834 which means that the footer stays in place right after the fold on the page, instead of being pushed to the bottom.
Fixes https://github.com/angular/components/issues/20049.

fix: footer not being pushed to the bottom of the page in guides

---

src/app/shared/stack-blitz/stack-blitz-writer.spec.ts
src/app/shared/stack-blitz/stack-blitz-writer.ts

In https://github.com/angular/components/commit/d00cb12582ab1265d38bb0f3012b7bd1adced97f the docs generation script changed the `indexFilename` to include the file extension which ends up propagating to TS imports inside generated Stackblitz examples. These changes strip the extension.
Fixes https://github.com/angular/components/issues/20061.

fix: remove extension from Stackblitz examples

---

src/app/shared/stack-blitz/stack-blitz-writer.ts

The `indexFilename` already includes the file extension so we don't need to add it again.

chore: fix double file extension

---

src/app/pages/component-category-list/component-category-list.html
src/app/pages/component-category-list/component-category-list.scss

Switch the component list to use the `img` element so we can take advantage of native lazy-loading.

 Use `img` element in component list w/ lazy loading

---

src/app/shared/documentation-items/documentation-items.ts

* Examples are matched using the prefix specified in documentation-items.ts
* Button & button-toggle both start with 'button-' prefix, so examples are getting mixed.
* We will exclude certain examples using "exclude" property.

docs(button): Exclude toggle button examples from button examples.

---

src/app/shared/documentation-items/documentation-items.ts

Some of the testing entry points were referring to incorrect modules (e.g. badge was pointing to button toggle). These changes fix them and add some of the newer harnesses that aren't in the docs.
Fixes https://github.com/angular/components/issues/20260.

fix: some testing entry points referring to wrong module

---

src/app/shared/example-viewer/example-viewer.html
src/app/shared/example-viewer/example-viewer.ts

Currently we end up throwing an error if an example is broken which will take down any components after it in the DOM. These changes add some null checks so only the broken component is affected.

fix: avoid breaking page if there's a broken example

---

src/app/shared/documentation-items/documentation-items.ts

We've recently added more test harnesses that weren't being reflected in the docs.
Fixes https://github.com/angular/components/issues/20507.

fix: add missing test harnesses

---

package.json

We recently removed the ngcc postinstall since the Angular
compiler webpack plugin dynamcially processed packages that
were imported. This reduced Yarn install time for the docs site.
Now due to a recent update of the CLI build-angular version,
the examples break because ngcc no longer processes entry-points
based on module dependencies, but rather only as per TypeScript
program source files/referenced files. This does not include the
docs-content as the examples are loaded lazily and aren't part of
the TS compilation.
Here is the related change in the CLI:
https://github.com/angular/angular-cli/commit/6670af2d3329959efb0e0831cf2105d9591d7475

build: re-add ngcc postinstall for docs content

---

src/app/pages/component-sidenav/component-sidenav.ts

Removes duplicate import of `MatSidenavModule` into `ComponentSidenavModule` (likely to have occurred during a merge conflict resolution somewhere between #697 & #698).

refactor: remove duplicate module import

---

README.md

Issue #870  :
Anchor link was not valid inside readme section.
Solution:
Replaced that with official material directory

Updated Material component  anchor link

---

src/app/pages/component-viewer/component-viewer.scss

Fixes the visibility of the anchor titles documentation UI which is currently clipped. This is done by assigning CSS `overflow: visible` property to the parent component - component-overview.
Fixes [20687](https://github.com/angular/components/issues/20687)
_**Before**_
_**After**_
The approach mentioned in [20687](https://github.com/angular/components/issues/20687) suggests removing the margin of -30px from `header-link`. This would make the header text start after 30px with nothing in between. The approach in this PR is taken to overcome this visual oddity.

Docs titles clipped on the left side - anchors not accessible

---

src/app/shared/documentation-items/documentation-items.ts

prefix `datepicker-` excludes date range picker examples

fix: include date range picker examples

---

angular.json
src/assets/stack-blitz/src/main.ts
src/environments/environment.ts
src/main.ts

The polyfills file was incorrectly imported through the `main` file
of the CLI project. This caused undesired CommonJS dependency
warnings for ZoneJS. We fix this by removing the import of the
polyfills and letting the CLI handle the polyfills as normally done
in fresh CLI projects.
Also disables the zone-error import from the devmode environment.
ZoneJS generally has the potential of hiding errors (as seen with
the `Object.defineProperty` patch that was enabled by default in
non-evergreen Zone bundles), so we should disable it. It seems
better aligning devmode as much as possible with prodmode to catch
issues more quickly. Debugging without `zone-error` is not any
different from common Angular/ZoneJS errors as seen in the components
or framework repositories.

build: fix angular cli commonjs warnings for polyfills

---

src/app/shared/stack-blitz/stack-blitz-writer.ts
src/assets/stack-blitz/src/index.html
src/assets/stack-blitz/src/styles.scss

We weren't generating a full valid HTML file when creating the `index.html` for Stackblitz which meant that if somebody creates a repository out of it, it won't work. These changes resolve the issue by providing the full HTML file.
Providing the full HTML also allows us to represent a real app better and to fix some issues like the one where the app background doesn't cover the whole page.
Fixes https://github.com/angular/components/issues/21461.

fix: generated Stackblitz examples not working when forked to a repo

---

src/_app-theme.scss
src/app/pages/component-sidenav/component-sidenav.ts
src/app/pages/not-found/_not-found-theme.scss
src/app/pages/not-found/index.ts
src/app/pages/not-found/not-found.html
src/app/pages/not-found/not-found.scss
src/app/pages/not-found/not-found.ts
src/app/routes.ts

Sets up a dedicated 404 page, rather than redirecting everything to the front page which doesn't tell the user that their link is incorrect. The design is based on the one from angular.io.
I also had to make some adjustments to the routing setup, because everything was being picked up by the `:section` route and we didn't have defined routes for `/cdk` and `/components` to which we link from the top nav.

feat: add 404 page

---

src/app/pages/component-viewer/component-viewer.ts
src/app/shared/doc-viewer/doc-viewer.ts

On the documentation page of a component, resizing down the width under 1200px makes the right sided table of contents disappears. By resizing the width to more than 1000px, the table of contents does not re-appear.
Navigate to any component documentation from the [overview](https://material.angular.io/components/categories).
Resize the width to less than 1200px.
Resize it back to more than 1200px.
=> the table of contents isn't present.
add change detection
trigger the event emitters to populate the toc
Closes [angular/components issue ](https://github.com/angular/components/issues/20315)

fix(toc): visibility on resizing

---

src/app/pages/component-viewer/component-api.html
src/app/pages/component-viewer/component-viewer.scss

- when there is plenty of room, the message is being wrapped due to the width
of the new parent span that was added in #717
Harness API docs aren't side-by-side

fix(component-viewer): Loading document... getting wrapped

---

src/app/shared/table-of-contents/table-of-contents.html

fix(toc): quickly switching to API tab can throw exceptions

---

src/styles/_markdown-theme.scss
src/styles/_markdown.scss

Adds some basic styles to clean up the appearance of the Markdown-generated tables.
**Before:**
**After:**

fix: add styling for markdown tables

---

src/app/shared/guide-items/guide-items.ts

Fixes a 404 due to a guide not being declared.
Fixes https://github.com/angular/components/issues/21853.

fix: declare duplicate theming guide

---

src/app/shared/example-viewer/example-viewer.html
src/app/shared/example-viewer/example-viewer.ts

Adds the ability to copy an anchor link to a specific example. Has a bit of extra logic to ensure that the browser actually scrolls the element into view.
Fixes https://github.com/angular/components/issues/21884.

feat: add button to copy link to example

---

firebase.json
tools/audit-docs.js

- update cache ages for different types of assets
- assets 6 months, CDN 1 year
- js/css that is hashed per build, 1 year
- webmanifest/ico 7 days, CDN 14 days
- CLI auto-inlined SVG in root dir 1 year
Relates to https://github.com/angular/angular/issues/37631
You can test this out for yourself against https://angularmaterial.dev/ using
- https://securityheaders.com/
- https://webpagetest.org/

feat: add CSP and recommended security headers to site

---

src/app/pages/component-category-list/component-category-list.ts
src/app/pages/component-sidenav/component-sidenav.ts
src/app/pages/component-viewer/component-viewer.ts
src/app/shared/carousel/carousel.spec.ts
src/app/shared/carousel/carousel.ts
src/app/shared/doc-viewer/doc-viewer.ts
src/app/shared/doc-viewer/header-link.ts
src/app/shared/example-viewer/code-snippet.ts
src/app/shared/example-viewer/example-viewer.html
src/app/shared/example-viewer/example-viewer.ts
src/app/shared/ga/ga.ts
src/app/shared/navbar/navbar.ts
src/app/shared/navigation-focus/navigation-focus.service.ts
src/app/shared/stack-blitz/stack-blitz-button.html
src/app/shared/stack-blitz/stack-blitz-button.ts
src/app/shared/svg-viewer/svg-viewer.ts
src/app/shared/table-of-contents/table-of-contents.ts
src/app/shared/theme-picker/theme-picker.ts
tsconfig.json

- fix related build errors
- complete `this._destroyed` in `ngOnDestroy()`
- replace use of deprecated `DomPortalHost` with `DomPortalOutlet`
Builds on PR https://github.com/angular/material.angular.io/pull/688

build: enable strictPropertyInitialization

---

src/assets/stack-blitz-tests/package.json
src/assets/stack-blitz/package.json

- for Angular v12.0.0-next.5 compatibility
- update Angular CLI to v12.0.0-next.5 as well
This doesn't actually fix StackBlitz for autocomplete or select. I've opened https://github.com/stackblitz/core/issues/1405 to try and get more information or assistance with that.

build: update StackBlitz demos to typescript 4.2

---

src/app/pages/guide-list/guide-list.scss

Fixes that the guides page has two scroll bars on Windows.
Fixes #945.

fix: double scroll bars on guides page

---

scenes/src/app/scene-viewer/scene-viewer.ts
scenes/src/app/scenes/autocomplete/autocomplete-scene.ts
scenes/src/app/scenes/menu/menu-scene.ts
scenes/src/app/scenes/ripples/ripples-scene.ts
scenes/src/app/scenes/select/select-scene.ts
scenes/src/app/scenes/slider/slider-scene.ts
scenes/src/app/scenes/tooltip/tooltip-scene.ts

The `yarn build:scenes` task was failing, because there were some `strictPropertyInitialization` errors.

build: fix compilation errors in scenes

---

src/assets/stack-blitz-tests/tsconfig.json
src/assets/stack-blitz/tsconfig.json

Fixes #940
You can test this on https://angularmaterial.dev/
As mentioned in #940, when a new release comes out, for 2-3 minutes after deployment, there will be CORS errors from their cache while the `ngcc` processes run (and AWS lambda times out) and eventually update their cache. We can minimize this by opening one of the StackBlitz examples right after deploying an update to any of the Components' packages.
This is likely worth trying since Angular v12 is making a significant push towards Ivy and we've been lagging a bit behind on this.

chore: enable Ivy in StackBlitz examples

---

firebase.json

- needed for `data:image/png;base64` images used in some examples
Fixes:

fix(csp): allow img-src of 'self'

---

firebase.json

- needed for `data:image/png;base64` images used in some examples
Fixes:

fix(csp): allow img-src of 'self' for v11.x

---

src/app/shared/stack-blitz/stack-blitz-button.ts
src/app/shared/stack-blitz/stack-blitz-writer.spec.ts
src/app/shared/stack-blitz/stack-blitz-writer.ts

When generating an example in Stackblitz, we have to create a `form` element and submit it to a specific URL. The `form` has to be created eagerly, because some browsers will block us from submitting it if it is created asynchronously.
As a result of this setup, we fire off a lot of HTTP requests when an example is rendered which slows the page down. These changes make the following improvements which shave off more than a second of scripting time when transitioning from the "Overview" to "Examples". I've used the datepicker examples as a benchmark.
1. Runs the HTTP requests outside of the Angular zone so that we don't trigger change detections once each request is resolved.
2. Caches the file content so that the user doesn't have to load the same file multiple times.
I've also fixed that …

perf: example rendering performance improvements

---

firebase.json
package.json
src/assets/versions.json
yarn.lock

- we can't remove this until we release v12 and switch the main site to it
- add CSP connect-src rule to allow getting the versions.json file
- allow downloading the versions.json from other origins like v10.material.angular.io
Relates to #962

fix(version-picker): restore the versions.json

---

src/styles/_api-theme.scss
src/styles/_api.scss

Replaces the `async` method marker with a generic marker that can also be used for static methods.
Related to https://github.com/angular/components/pull/22786.

refactor: add modifier badge tag

---

src/styles/_api-theme.scss

* Fixes that links inside the API reference weren't themed, causing them to have a poor contrast ratio.
* Simplifies the Sass in the API theme.
Fixes https://github.com/angular/components/issues/14615.

fix: use theme color for link inside the API reference

---

src/app/shared/documentation-items/documentation-items.ts

Fixes a failing test because the links weren't sorted alphabetically.

fix: sort links alphabetically

---

src/_app-theme.scss
src/app/app-module.ts
src/app/material-docs-app.html
src/app/shared/cookie-popup/_cookie-popup-theme.scss
src/app/shared/cookie-popup/cookie-popup-module.ts
src/app/shared/cookie-popup/cookie-popup.html
src/app/shared/cookie-popup/cookie-popup.scss
src/app/shared/cookie-popup/cookie-popup.ts

Due to legal requirements we have to have a cookie disclaimer popup. It is always shown until the user agrees to it. After the user has agreed, the popup won't be shown on subsequent sessions.
Fixes https://github.com/angular/components/issues/22746.
**Note:** currently this doesn't have any accessibility treatment, because I'm not sure what the correct approach would be. I assume that we'd have to move focus into the cookie popup since it has more than one button, but its `role` is currently either `status` or `alert` which may not make sense to receive focus and to contain buttons.

feat: add cookie popup

---

src/app/shared/doc-viewer/doc-viewer.spec.ts
src/app/shared/doc-viewer/doc-viewer.ts

Currently we fetch a doc every time we need to display it which means that user navigating between two pages will have to request the same information multiple times.
These changes add a caching layer since the information isn't going to change.

fix: cache fetched docs

---

src/app/shared/documentation-items/documentation-items.ts

Follow-up to https://github.com/angular/components/pull/22829. Exposes the CDK accordion docs in the navigation.

feat: expose CDK accordion docs

---

src/app/pages/guide-list/guide-list.scss
src/app/pages/guide-list/guide-list.spec.ts

Fixes that the guide tiles can overlap the footer on smaller screens.
Fixes https://github.com/angular/components/issues/22860.

fix: guides overlapping footer on narrow screens

---

src/app/pages/homepage/_homepage-theme.scss
src/app/pages/homepage/homepage.html
src/app/pages/homepage/homepage.scss
src/app/shared/carousel/carousel.html
src/app/shared/carousel/carousel.scss
src/app/shared/carousel/carousel.spec.ts
src/app/shared/carousel/carousel.ts

Currently the carousels on the front page don't align with any other elements on the page which looks odd. This seems to be due to a limitation where the item size has to be passed in to the carousel.
These changes reimplement the carousel, making it more flexible and allowing it to handle any size of items and any spacing. The new carousel is used on the frontpage to lay out the items in a way that aligns with the rest of the content.
Before:
After:

feat: more flexible carousels and fix homepage alignment

---

src/assets/stack-blitz/src/main.ts

Companion PR to https://github.com/angular/components/pull/22837. Removes the default form field appearance so that we get a consistent result between the docs site and Stackblitz.

refactor: remove default form field appearance in Stackblitz

---

src/styles/_markdown-theme.scss
src/styles/_markdown.scss
src/styles/_tables-theme.scss
src/styles/_tables.scss

* Aligns the design between the tables inside markdown and the tables in the API docs. I chose to go with the design from the API docs, because the separation between cells is much better.
* Fixes the poor color contrast on the table border by using the correct theming variables.
* Removes the table box shadow and fixes up some spacings to make the tables look better.
Before:
After (note that this applies to tables in the API docs too):

fix: align and clean up table design

---

README.md

Fixes "Development Setup" list to correctly nest yarn commands.

docs(readme): fix development setup list format

---

src/app/shared/table-of-contents/table-of-contents.ts

Fixes that the table of contents was triggering change detections while scrolling.

perf: avoid triggering change detection on scroll

---

src/styles/_markdown.scss

* Fixes that selecting the header text also selects the word `link` from the icon.
* Tries to center the icon a little bit better.

fix: prevent users from selecting link icon text

---

src/assets/stack-blitz/tsconfig.json

Stackblitz has a race condition that an cause issues when running ngcc against our packages, resulting in errors.
These changes temporarily disable Ivy until we can start using the linker.

fix: temporarily disable Ivy on Stackblitz

---

src/app/shared/documentation-items/documentation-items.spec.ts
src/app/shared/documentation-items/documentation-items.ts

De-duplicates some logic and adds programmatic sorting of the menu items so that we don't have to do it manually. Currently the "Component harnesses" menu item is out of order.

fix: ensure that menu items are always sorted

---

src/assets/stack-blitz/src/app/material-module.ts

Currently the stackblitz demo for [accordion](https://material.angular.io/cdk/accordion/overview) doesn't work by default.  This adds CdkAccordionModule to material-module to fix this issue.

fix: include cdkAccordionModule in material-module for accordion stackblitz demo

---

src/assets/stack-blitz/tsconfig.json

Stackblitz has a race condition that causes issues when running ngcc against our packages, resulting in errors.
These changes temporarily disable Ivy until we can start using the linker.
(cherry picked from commit f41506ac505206763b384808e196a6bb2459d1d5)
Closes #1076

fix: temporarily disable Ivy on Stackblitz (#1050)

---

src/app/shared/navbar/navbar.html

The class was already there but not used.

fix: github icon was not centered on mobile

---

src/assets/stack-blitz/src/test.ts
yarn.lock

We removed the test environment calls from the harness example spec
files so that the standard CLI `test.ts` file can initialize the
test browser environment. This commit updates the SHA of the docs
content and re-adds the `test.ts` init environment logic.
https://github.com/angular/components/commit/88b718e8d947def1dc8c03050a4fb12fbe1e4ace

refactor: update stackblitz boilerplate to setup test environment

---

src/app/shared/version-picker/version-picker.ts

PR #645 erroneously changed this to a relative url. We want this to always use the latest material.angular.io so that we don't have to update old branches for new major versions.

Always load versions from latest material.angular.io

---

src/app/shared/stack-blitz/stack-blitz-writer.ts

A `favicon.ico` is stored in `assets/stack-blitz/src` but not sent to stackBlitz. So despite `favicon.ico` in assets, it is currently not used anywhere.
Another solution would be to delete `favicon.ico`.

refactor: transfer favicon to stackBlitz

---

tools/deploy.sh

Fixes the tools/deploy.sh script failing silently when determining if it
has a pre-release version
```
cdk_prerelease=$(cat package.json | grep cdk | egrep next\|rc
```
^ Since this script has `pipefail` set, egrep would exit with code 1 and
cause the entire script to exit with code 1. Fixes this by adding an `||
true`, so that we don't crash when the script cannot recognize a
pre-release version. egrep is expected to exit with 1 if this is neither
a next nor rc version

build: fix crash in deploy script due to pipefail

---

package.json
scenes/src/test.ts
src/test.ts
yarn.lock

* Cleans up the code that explicitly enables `TestsBed` teardown since it's enabled by default.
* Updates to the same MDC version as the main repo.

refactor: clean up explicit TestBed teardown and bump MDC version

---

src/app/shared/stack-blitz/stack-blitz-writer.spec.ts
src/app/shared/stack-blitz/stack-blitz-writer.ts
src/assets/stack-blitz/angular.json
src/assets/stack-blitz/src/index.html

Fixes the forking and saving functionality for WebContainer StackBlitz
examples. The saving/forking functionality did not work (no proper error though)
because we delivered a binary `.ico` file to StackBlitz.
To fix the examples, we will remove the `favicon.ico` file, even the goal
was to keep the examples as equivalent as possible to a `ng new`-created app.
It's surprising this worked in the past, but the StackBlitz SDK mentions that no binary files
are supported and this breaks the saving, according to my investigation. Still would be good
if StackBlitz would have a better error indication I guess (lots of people submitted issues on their end)

Fix forking and saving for webcontainer stackblitz examples

---

package.json
yarn.lock

The docs app currently deployed to `material.angular.io` is for Angular
Components v13, but relies on docs-content from `master` i.e. v14-next.
We should scope the docs-content to v13.2.x (the latest and last minor for
v13) for the v13.x docs deployment.

Fix docs-content version mismatch for v13.x docs deployment

---

.gitignore
firebase.json
src/app/shared/normalized-version.ts
src/app/shared/stack-blitz/stack-blitz-writer.ts
src/app/shared/version-picker/version-picker.ts
tools/deploy.sh
tools/lighthouse-audit.js

Sets up a Firebase hosting target name for the docs hosting. This is
useful when we want to support multi-sites for a single project.
This is currenlty a noop but will be useful when we auto-deploy
the docs site leveraging Firebase multi-sites (like FW does)

build: set firebase hosting target name to support multi-site

---

.circleci/config.yml

CircleCI always rebases branches on top of `master` currently, breaking
CI in all other branches like `13.x`.
We should let the orb auto-discover the target branch..

build: fix circleci rebase to work with other branches than `master`

---

src/assets/stack-blitz/angular.json

The prompt will prevent the examples from running automatically in
StackBlitz, now requiring user action to proceed with serving.
We should disable this as this setting is not persisted across
StackBlitz projects anyway..

Avoid analytics prompt of CLI in stackblitz examples

---

firebase.json

e.g. StackBlitz assets should not be cached indefinitely as otherwise e.g. we might end up with Angular v13 and CDK/Material v14, breaking examples..

Rework caching header rules in an attempt to fix caching issues

---

src/assets/stack-blitz/package-lock.json
src/assets/stack-blitz/package.json

Adds `@angular/material-moment-adapter` and `moment` to the package.json
on stackblitz examples. This fixes the "Cannot find module 'moment' or
its corresponding type declarations." in some examples.
Fixes https://github.com/angular/components/issues/25136

fix: add material-moment-adapter to stackblitz dependencies

---

src/app/shared/navbar/navbar.scss
src/app/shared/version-picker/version-picker.scss
src/app/shared/version-picker/version-picker.ts

The MDC buttons have a more specific selector for the button color which was breaking the color contrast check.

fix: lighthouse check failing in v15

---

src/app/shared/footer/footer.html
src/app/shared/footer/footer.ts

Update the copyright to change it dynamically using JS, so now don't need to do a deploy just to update the footer.

fix: add dynamic copyright

---

.bazelrc

The experimental allow tags propagation flag is a `BuildLanguage` option and causes all Starlark code to be re-invoked. This causes a slow-down when switching between bazel query/ bazel build because the option is not set for `bazel query`.
We fix it by applying the option to all commands, using `common`.

build: avoid unnecessary re-evaluation of starlark code

---

.aspect/rules/external_repository_action_cache/npm_translate_lock_LTE4Nzc1MDcwNjU=
.circleci/config.yml
WORKSPACE.bazel
pnpm-lock.yaml

This is a pre-factor to hoisting this repository into the components repository. May as well get it onto the latest version of rules_js first.
@devversion, the latest version of rules_js will keep your pnpm-lock.yaml file up-to-date automatically (when your source-of-truth is a yarn.lock file) when any of the inputs to the npm_translate_lock repository rule change. The `.aspect/rules/external_repository_action_cache/npm_translate_lock_LTE4Nzc1MDcwNjU=` file acts like an action cache to know when to re-run `pnpm import` to update the pnpm lock file.

build: update to aspect_bazel_lib 1.28.0 and aspect_rules_js 1.20.1

---

src/assets/stack-blitz/src/test.ts

Updates the test.ts to use the correct API for discovering the test files.
Fixes https://github.com/angular/components/issues/26806.

fix: harnesses not working on Stackblitz

---

src/app/shared/stack-blitz/stack-blitz-writer.ts
src/assets/stack-blitz/.stackblitzrc

This PR replace the use of `turbo` with `yarn` as `turbo` is being deprecated and StackBlitz has support for `yarn` v1 out of the box.
See related PR: https://github.com/angular/angular/pull/50576

fix: replace use of turbo with yarn

---

.aspect/rules/external_repository_action_cache/npm_translate_lock_LTE4Nzc1MDcwNjU=
.circleci/config.yml
BUILD.bazel
package.json
pnpm-lock.yaml
tools/audit-docs.js
tools/lighthouse-audit.mjs
yarn.lock

Fixes the page audit script that has been broken for a while now. To do this, I had to update to the latest versions of `lighthouse` and `puppeteer`. This in turn meant that I had to convert `lighthouse-audit.js` to ESM, because `lighthouse` started using ESM as well.

Fix page audit script

---

.circleci/config.yml
src/app/pages/homepage/homepage.ts
src/app/shared/footer/footer.ts
src/app/shared/navbar/navbar.ts

For security's sake the entire hostname should be checked against, not just that it starts with the hostname, otherwise another domain could just include this as a subdomain

fix: directly check if the hostname is the expected hostname instead of just starting with the hostname

---

src/assets/stack-blitz/package.json
src/assets/stack-blitz/src/main.ts
src/assets/stack-blitz/yarn.lock

We weren't importing `@angular/localize` into the Stackblitz template which leads to errors for the examples that use it.
Fixes https://github.com/angular/components/issues/27645.

Fix examples using $localize

---

src/app/shared/guide-items/guide-items.ts

Removes the MDC migration guide since we've removed the migration in v18.

fix: remove MDC migration guide

---

src/app/material-docs-app.html
src/app/material-docs-app.ts

The nav bar wasn't meant to have an elevation, it just wasn't working prior to a fix earlier today.

fix: remove elevation from nav bar

---

.circleci/config.yml
.github/workflows/ci.yml

The CircleCI based CI workflow for the main branch and all potential release branches is now execute via Github Actions.  The CircleCI configuration temporarily is still present with an automatically passing test to prevent CircleCI failure. An additional direct build step has also been added to the build job for both PR and main CI workflows to ensure that the build that occurs during the deployment script continues to function.

ci: convert main CI workflow to Github Actions

---

.aspect/rules/external_repository_action_cache/npm_translate_lock_LTE4Nzc1MDcwNjU=
.yarnrc.yml
package.json
pnpm-lock.yaml
yarn.lock

When performing a yarn-based package installation, only a specific group of dependencies will now have postinstall scripts executed. This not only provides additional security benefits but also reduced the amount of script execution that occurs during each install. The workspace scripts are automatically allowed and additional specific packages can be allowed as needed.

build: restrict postinstall scripts during package installation

---

src/app/shared/table-of-contents/table-of-contents.ts

Fixed issue of h2 titles not being displayed in the table of contents
Fixes #29071

docs-bug(Theming Angular Material): table of contents misses h2 headers

---

src/app/pages/component-sidenav/component-nav.html
src/app/pages/component-sidenav/component-sidenav.ts
src/app/shared/carousel/carousel.ts
src/app/shared/doc-viewer/doc-viewer.ts
src/app/shared/doc-viewer/header-link.ts
src/app/shared/example-viewer/code-snippet.html
src/app/shared/example-viewer/code-snippet.ts
src/app/shared/table-of-contents/table-of-contents.ts

Migrates all inputs to signal inputs using the upcoming automated migration.

refactor: migrate to signal inputs using automated migration

---

scenes/src/app/scene-viewer/scene-viewer.ts
scenes/src/app/scenes/autocomplete/autocomplete-scene.ts
scenes/src/app/scenes/menu/menu-scene.ts
scenes/src/app/scenes/ripples/ripples-scene.ts
scenes/src/app/scenes/select/select-scene.ts
scenes/src/app/scenes/tooltip/tooltip-scene.ts
src/app/pages/component-sidenav/component-sidenav.html
src/app/pages/component-sidenav/component-sidenav.spec.ts
src/app/pages/component-sidenav/component-sidenav.ts
src/app/pages/component-viewer/component-viewer.ts
src/app/shared/carousel/carousel.ts
src/app/shared/example-viewer/code-snippet.ts
src/app/shared/example-viewer/example-viewer.html
src/app/shared/example-viewer/example-viewer.ts

Runs the signal queries migration in this repository.

refactor: switch to signal queries

---

package.json
src/app/pages/component-sidenav/component-sidenav.ts
src/app/pages/component-viewer/component-styling.html
src/app/pages/component-viewer/component-styling.ts
src/app/pages/component-viewer/component-viewer.spec.ts
src/app/pages/component-viewer/component-viewer.ts
src/app/pages/component-viewer/token-name.ts
src/app/pages/component-viewer/token-table.html
src/app/pages/component-viewer/token-table.scss
src/app/pages/component-viewer/token-table.ts
src/app/shared/documentation-items/documentation-items.ts
yarn.lock

Adds a "Styling" page to each component that tells users how to customize the component's styles.

Add styling page to the docs

---

src/app/pages/component-viewer/token-table.scss
src/app/pages/component-viewer/token-table.ts

Fixes the following issues with the styling page:
* The table header background wasn't themed correctly.
* The filters looked weird on smaller screens.
* Filtering was case-sensitive.

Follow-up fixes for the styling page

---

src/app/shared/documentation-items/documentation-items.ts

renames `test-harnesses` route to `testing` as entry point for `cdk/testing` is latter in packages repository, this was causing links to not work properly when redirected to a route with `test-harnesses`
---
some examples:
https://material.angular.io/components/input/api#MatNativeOptionHarness
https://material.angular.io/cdk/test-harnesses/api#TestbedHarnessEnvironment

fix: routing path for `cdk/testing`

---

src/app/shared/documentation-items/documentation-items.ts

Hides the styling page for the ripple since it's part of `core`.
Fixes https://github.com/angular/components/issues/30098.

fix: hide ripple styling page

---

src/app/shared/doc-viewer/deprecated-tooltip.ts
src/app/shared/doc-viewer/doc-viewer-module.ts
src/app/shared/doc-viewer/doc-viewer.spec.ts
src/app/shared/doc-viewer/doc-viewer.ts
src/styles/_api.scss

previously we weren't showing any other information other than `breaking-change` for deprecated fields, this commit adds a component that protrays information regarding deprecation in tooltips rather than `title` attribute
closes angular/components#29839

feat: show deprecated related information in `material/tooltip`
